### PR TITLE
benchmark submission method updates, Cheyenne can run the benchmark?

### PR DESCRIPTION
**Pull request by tinaok**
@kpaul @andersy005 
Hello, I made some update of benchmark, would you mind running them on Cheyenne with Cheyenne.yaml to see if it runs ok on your site?

### CODE REVIEW

**Comment by tinaok** [comment]
with lazy bug fix for issue #14  and #15.  (for #15, weight is not added)

**Comment by tinaok** [comment]
thanks @andersy005, I guess it needs to be 'merged' before you test the new update, but 'I do not have the rights to 'merge' the pull request to this repo ( because I'm not yet tagged as Pangeo community member? )

**Comment by andersy005** [comment]
> I guess it needs to be 'merged' before you test the new update

I am going to checkout your master branch and that's what I will use

**Comment by andersy005** [comment]
@tinaok 

1) 
In your `hal.yaml` config file, you have

```yaml
  chunk_size:
    - 512MB
    - 1024MB
    - 2048MB
    - 4096MB
```

However, when I look at the output in `hal.ipynb`, I am noticing `chunk_sizes` that were not specified in this config

e.g.:

`benchmark start with: worker_per_node=1, num_nodes=1, chunk_size=64MB, chunking_scheme=spatial, chunk per worker=10
`

It's not clear to me where the `chunk_size=64MB` is coming from. 

I am still trying to figure out how the new changes affect the code base since I haven't looked at this code base in the last 2-3 months. 


2) 

```yaml
  chunk_size:
    - 512MB
    - 1024MB
    - 2048MB
    - 4096MB
```

These chunk sizes are way bigger than the recommended ~120MB. Wouldn't this end up skewing the results?

Ccing @kmpaul since he probably looked at this code base a few days/weeks ago.

**Comment by tinaok** [comment]
hi @andersy005,
Thank you for working on this.
The reason why hal.yaml does not correspond to output  of hal.ipynb, is that I made several run using different hal.yaml, and I did not push all of the result (csv or other outputs like hal.ipynb) to GitHub. 
The hal.yaml with huge chunk_size is for my latest tests which I did not push since It was just to make some continuity of curves, and result was still experimental.
I can share them with you on gist, I'll send you the link by e-mail.   
Sorry for confusing you, I should have putted back my old hal.yaml.

**Comment by andersy005** [comment]
Hi @tinaok,

Thank you for getting back to me and the clarification. I will take another look this weekend, and will try running the benchmarks on Cheyenne too. Once I have the results, I will let you know

**Comment by andersy005** [comment]
@tinaok, 

Thank you for your patience! I am swamped with other tasks at work right now, and unfortunately, I won't be able to run the benchmarks soon. We could go ahead and merge this for the time being so as to not block you from moving forward. When I get time in the coming weeks, I can  run the benchmarks on Cheyenne, and get back to you. Would this work for you?

**Pull request merged**
